# Application bindings
bindd = SUPER, RETURN, Terminal, exec, xdg-terminal-exec --dir="$(omyvoid-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omyvoid-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, nautilus --new-window "$(omyvoid-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omyvoid-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omyvoid-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omyvoid-launch-editor

# Add extra bindings
# bindd = SUPER SHIFT, A, ChatGPT, exec, omyvoid-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omyvoid Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omyvoid menu, exec, omyvoid-menu
