#!/bin/bash

set -euo pipefail

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
failures=0

ok() { printf 'ok - %s\n' "$1"; }
nok() { printf 'not ok - %s\n' "$1" >&2; failures=$((failures + 1)); }
assert_file_contains() {
  local description=$1 file=$2 pattern=$3
  grep -Eq "$pattern" "$file" && ok "$description" || nok "$description"
}

echo '# Shell syntax'
while IFS= read -r script; do
  [[ $(head -n 1 "$script") == *python* ]] && continue
  bash -n "$script" || nok "bash syntax: ${script#"$ROOT"/}"
done < <(find "$ROOT/bin" "$ROOT/install" "$ROOT/release" "$ROOT/test" -type f -name '*.sh' -o -path "$ROOT/bin/omyvoid*" | sort)
(( failures == 0 )) && ok 'all shell entry points parse'

echo '# Distribution/runtime boundary'
if rg -n -i '\b(apt-get|apt-cache|add-apt-repository|dpkg-query|snapd|flatpak|update-initramfs|casper|uwsm|systemctl)\b' \
  "$ROOT/bin" "$ROOT/install" "$ROOT/default" "$ROOT/config" "$ROOT/installer/src" \
  -g '!*.png' >/tmp/omyvoid-forbidden-runtime.log; then
  cat /tmp/omyvoid-forbidden-runtime.log >&2
  nok 'product sources contain no inherited package-manager or init runtime'
else
  ok 'product sources contain no inherited package-manager or init runtime'
fi

if rg -n -i 'omybuntu|OMYBUNTU' "$ROOT/bin" "$ROOT/install" "$ROOT/default" "$ROOT/config" "$ROOT/installer/src" -g '!*.png'; then
  nok 'product paths and public variables use Omyvoid naming'
else
  ok 'product paths and public variables use Omyvoid naming'
fi

assert_file_contains 'base installer requires Void Linux' "$ROOT/install/preflight/all.sh" '^.*ID=void'
assert_file_contains 'base installer requires glibc' "$ROOT/install/preflight/all.sh" 'GNU_LIBC_VERSION'
assert_file_contains 'base installer rejects Secure Boot' "$ROOT/install/preflight/all.sh" 'Disable Secure Boot'
assert_file_contains 'XBPS is the package installation backend' "$ROOT/bin/omyvoid-pkg-add" 'xbps-install'

echo '# Storage and installer'
for subvolume in '@' '@home' '@log' '@xbps' '@snapshots'; do
  grep -Fq "\"$subvolume\"" "$ROOT/installer/src/install.rs" \
    && ok "installer creates $subvolume" || nok "installer creates $subvolume"
done
assert_file_contains 'root mounts use Btrfs compression' "$ROOT/installer/src/install.rs" 'subvol=@,noatime,compress=zstd'
assert_file_contains 'installer formats LUKS2' "$ROOT/installer/src/install.rs" '"luks2"'
assert_file_contains 'LUKS2 uses Argon2id' "$ROOT/installer/src/install.rs" '"argon2id"'
assert_file_contains 'installer creates a 2 GiB ESP' "$ROOT/installer/src/install.rs" 'ESP_BYTES: u64 = 2 \* 1024 \* 1024 \* 1024'
assert_file_contains 'installer backs up the Windows GPT before alongside changes' "$ROOT/installer/src/install.rs" 'partition-table\.gpt'
if rg -n 'mkfs\.(ext|xfs)|mkswap|swap partition' "$ROOT/installer/src"; then
  nok 'installer exposes only Btrfs root and no swap partition'
else
  ok 'installer exposes only Btrfs root and no swap partition'
fi

echo '# Limine and UKIs'
assert_file_contains 'Limine branding is Omyvoid' "$ROOT/default/limine/limine.conf" '^interface_branding: Omyvoid Bootloader$'
for color in 111c18 090f0d 509475 c1c497 f7e8b2; do
  grep -iq "$color" "$ROOT/default/limine/limine.conf" && ok "Limine palette contains #$color" || nok "Limine palette contains #$color"
done
assert_file_contains 'UKIs are assembled with ukify' "$ROOT/bin/omyvoid-uki-build" '^ukify build'
assert_file_contains 'UKI initramfs is generated by dracut' "$ROOT/bin/omyvoid-uki-build" '^dracut '
assert_file_contains 'Void packaged EFI stub is used' "$ROOT/bin/omyvoid-uki-build" 'systemd/boot/efi/linuxx64\.efi\.stub'
assert_file_contains 'canonical Limine config is written atomically' "$ROOT/bin/omyvoid-boot-refresh" 'mv -f "\$tmp" "\$ESP_PATH/limine\.conf"'
if rg -n '(cp|install|mv|tee).*EFI/(Limine|Omyvoid|BOOT)/limine\.conf' "$ROOT/bin" "$ROOT/install/config"; then
  nok 'no secondary Limine configuration is created below EFI'
else
  ok 'no secondary Limine configuration is created below EFI'
fi

current_line=$(grep -n '^/Omyvoid$' "$ROOT/bin/omyvoid-boot-refresh" | cut -d: -f1)
fallback_line=$(grep -n '^/Omyvoid fallback' "$ROOT/bin/omyvoid-boot-refresh" | cut -d: -f1)
snapshot_line=$(grep -n "echo '/Snapshots'" "$ROOT/bin/omyvoid-boot-refresh" | cut -d: -f1)
windows_line=$(grep -n '^/Windows Boot Manager' "$ROOT/bin/omyvoid-boot-refresh" | cut -d: -f1)
if (( current_line < fallback_line && fallback_line < snapshot_line && snapshot_line < windows_line )); then
  ok 'installed Limine entries follow current, fallback, snapshots, Windows order'
else
  nok 'installed Limine entries follow current, fallback, snapshots, Windows order'
fi

echo '# Snapshots and recovery'
assert_file_contains 'Snapper retains at most five numbered snapshots' "$ROOT/default/snapper/root" '^NUMBER_LIMIT="5"$'
assert_file_contains 'Snapper timeline is disabled' "$ROOT/default/snapper/root" '^TIMELINE_CREATE="no"$'
assert_file_contains 'snapshot boot uses a temporary OverlayFS' "$ROOT/default/dracut/95omyvoid-snapshot-overlay/omyvoid-snapshot-overlay.sh" 'mount -t overlay'
assert_file_contains 'restore saves the current root as a recovery subvolume' "$ROOT/bin/omyvoid-snapshot" 'recovery="@recovery-\$stamp"'
assert_file_contains 'restore rebuilds boot from the selected writable root' "$ROOT/bin/omyvoid-snapshot" 'refresh_boot_for_root "\$top/@"'
if grep -Eq 'mv .*@home|snapshot .*@home|delete .*@home' "$ROOT/bin/omyvoid-snapshot"; then
  nok 'snapshot restoration never replaces home'
else
  ok 'snapshot restoration never replaces home'
fi
assert_file_contains 'live recovery can unlock LUKS' "$ROOT/bin/omyvoid-recovery" 'cryptsetup open'
assert_file_contains 'live recovery can reinstall Limine' "$ROOT/bin/omyvoid-recovery" 'omyvoid boot repair'

echo '# runit and desktop'
assert_file_contains 'system services are enabled in runit' "$ROOT/install/config/runit.sh" '/etc/sv/'
assert_file_contains 'user services are supervised by runsvdir' "$ROOT/default/hypr/autostart.conf" 'runsvdir -P'
assert_file_contains 'audio user service includes PipeWire' "$ROOT/install/config/runit.sh" 'install_user_service pipewire pipewire'
assert_file_contains 'SDDM launches Hyprland directly' "$ROOT/install/login/sddm.sh" 'CompositorCommand=Hyprland --config'

wallpaper_count=$(find "$ROOT/themes/omyvoid/backgrounds" -maxdepth 1 -type f | wc -l)
(( wallpaper_count == 4 )) && ok 'desktop exposes four Omyvoid wallpapers' || nok 'desktop exposes four Omyvoid wallpapers'
[[ -f $ROOT/default/limine/omyvoid-boot.png ]] && ok 'separate optimized boot wallpaper exists' || nok 'separate optimized boot wallpaper exists'

echo '# ISO definition'
for entry in 'Start Omyvoid Live' 'Start with safe graphics' 'Open recovery' 'Start installer'; do
  grep -Fq "/$entry" "$ROOT/install/iso/limine.conf" && ok "live menu contains $entry" || nok "live menu contains $entry"
done
assert_file_contains 'ISO is based on void-mklive' "$ROOT/install/iso/build-iso.sh" 'void-linux/void-mklive'
assert_file_contains 'ISO final image is authored with xorriso' "$ROOT/install/iso/build-iso.sh" '^xorriso -as mkisofs'
assert_file_contains 'ISO uses a UEFI El Torito image' "$ROOT/install/iso/build-iso.sh" '-eltorito-alt-boot -e boot/limine-uefi\.img'
assert_file_contains 'ISO embeds the offline repository' "$ROOT/install/iso/build-iso.sh" 'image_dir/repository'
assert_file_contains 'remote Omyvoid repository is optional during ISO bootstrap' "$ROOT/install/iso/build-iso.sh" 'if \[\[ -n \$\{OMYVOID_XBPS_REPOSITORY:-\} \]\]'
assert_file_contains 'void-mklive is the only privileged ISO stage' "$ROOT/install/iso/build-iso.sh" 'sudo_args\[@\].*mklive\.sh'
if rg -n -- '-b |eltorito-boot|legacy-bios|bios-cd' "$ROOT/install/iso/build-iso.sh"; then
  nok 'first ISO series does not configure Legacy BIOS boot'
else
  ok 'first ISO series does not configure Legacy BIOS boot'
fi

echo '# XBPS repository templates'
for package in elephant omyvoid-limine-entry-tool omyvoid-limine-snapper-sync omyvoid-dracut-snapshot; do
  [[ -f $ROOT/xbps-src/srcpkgs/$package/template ]] && ok "XBPS template exists: $package" || nok "XBPS template exists: $package"
  grep -Fq "$package" "$ROOT/release/build-xbps-repo.sh" && ok "XBPS repository builds: $package" || nok "XBPS repository builds: $package"
done
for package in omyvoid-dracut-snapshot omyvoid-limine-entry-tool omyvoid-limine-snapper-sync; do
  assert_file_contains "XBPS package declares its homepage: $package" "$ROOT/xbps-src/srcpkgs/$package/template" '^homepage="https://github\.com/erickdevit/omyvoid"$'
  assert_file_contains "XBPS package installs its MIT license: $package" "$ROOT/xbps-src/srcpkgs/$package/template" 'vlicense.*FILESDIR.*/LICENSE'
done
assert_file_contains 'XBPS build stages licenses for internal packages' "$ROOT/release/build-xbps-repo.sh" 'workspace/LICENSE'
assert_file_contains 'Walker launches the packaged Elephant binary from PATH' "$ROOT/bin/omyvoid-launch-walker" 'setsid elephant'

echo '# Supported optional applications'
assert_file_contains 'Chromium is offered by the browser installer' "$ROOT/bin/omyvoid-install-browser" 'chromium\|firefox'
assert_file_contains 'Chromium is the default HTTP browser' "$ROOT/install/config/mimetypes.sh" 'default-web-browser chromium\.desktop'
assert_file_contains 'Google account support is conditional in the service menu' "$ROOT/bin/omyvoid-menu" "! grep -q -- '--oauth2-client-id'"
assert_file_contains 'Google account credentials survive Chromium refreshes' "$ROOT/bin/omyvoid-refresh-chromium" 'omyvoid-install-chromium-google-account'
if rg -n 'chrome|brave|brave-origin|edge|zen' "$ROOT/bin/omyvoid-install-browser"; then
  nok 'browser installer exposes only Chromium and Firefox'
else
  ok 'browser installer exposes only Chromium and Firefox'
fi

unsupported_installers=(
  omyvoid-install-ai-ollama
  omyvoid-install-editor-cursor
  omyvoid-install-gaming-heroic
  omyvoid-install-gaming-minecraft
  omyvoid-install-gaming-moonlight
  omyvoid-install-nordvpn
  omyvoid-install-once
  omyvoid-install-service-sunshine
  omyvoid-install-zed
)
for command in "${unsupported_installers[@]}"; do
  [[ ! -e $ROOT/bin/$command ]] && ok "unsupported installer removed: $command" || nok "unsupported installer removed: $command"
done

(( failures == 0 )) || exit 1
