# Application bindings
bindd = SUPER, RETURN, Terminal, exec, xdg-terminal-exec --dir="$(omyvoid-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, xdg-terminal-exec --dir="$(omyvoid-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER SHIFT, RETURN, Browser, exec, omyvoid-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, nautilus --new-window "$(omyvoid-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omyvoid-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omyvoid-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omyvoid-launch-or-focus spotify
bindd = SUPER SHIFT ALT, M, Music TUI, exec, omyvoid-launch-or-focus-tui cliamp
bindd = SUPER SHIFT, N, Editor, exec, omyvoid-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omyvoid-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omyvoid-launch-or-focus ^signal$ "signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omyvoid-launch-or-focus ^obsidian$ "obsidian"
bindd = SUPER SHIFT, W, Typora, exec, typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, bitwarden

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omyvoid-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, omyvoid-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, C, Calendar, exec, omyvoid-launch-webapp "https://app.hey.com/calendar/weeks/"
bindd = SUPER SHIFT, E, Email, exec, omyvoid-launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omyvoid-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omyvoid-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omyvoid-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, P, Google Photos, exec, omyvoid-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bindd = SUPER SHIFT, X, X, exec, omyvoid-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omyvoid-launch-webapp "https://x.com/compose/post"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omyvoid Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omyvoid menu, exec, omyvoid-menu

# Logitech MX Keys
# bind = SUPER SHIFT, S, exec, omyvoid-capture-screenshot      # Print Screen Button
# bind = SUPER, H, exec, voxtype record toggle                 # Dictation Button
# bind = SUPER, PERIOD, exec, omyvoid-launch-walker -m symbols # Emoji Button
