general {
    lock_cmd = omybuntu-system-lock                         # lock screen and 1password
    before_sleep_cmd = OMYBUNTU_LOCK_ONLY=true omybuntu-system-lock    # lock before suspend without scheduling display off.
    after_sleep_cmd = sleep 1 && omybuntu-system-wake                 # delay for PAM readiness, then turn on display.
    inhibit_sleep = 3                                      # wait until screen is locked
}

# Start screensaver after 5 minutes
listener {
    timeout = 300
    on-timeout = pidof hyprlock || omybuntu-launch-screensaver
}

# Lock system after 7 minutes (screensaver resets idle timer, so have to just do half + 2s margin)
listener {
    timeout = 422
    on-timeout = omybuntu-system-lock
    on-resume = omybuntu-system-wake
}

# Turn off screen 1 minute after lock
listener {
    timeout = 482
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend after 15 minutes total idle time
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
