general {
    col.active_border = rgba(8a8588ee) rgba(e2dddcee) 45deg
    col.inactive_border = rgba(584e51aa)
}

group {
    col.border_active = rgba(8a8588ee) rgba(e2dddcee) 45deg
    col.border_inactive = rgba(584e51aa)
}
