ESP_PATH="/boot"
OMYVOID_ROOT_SUBVOLUME="@"
OMYVOID_KERNEL_CMDLINE="rw quiet splash loglevel=3 rd.udev.log_level=3"
OMYVOID_WINDOWS_EFI_UUID=""
OMYVOID_WINDOWS_EFI_PATH="/EFI/Microsoft/Boot/bootmgfw.efi"
OMYVOID_KEEP_SNAPSHOTS=5
