timeout: 3
default_entry: 1
remember_last_entry: yes
interface_branding: Omyvoid Bootloader
interface_branding_colour: 509475
interface_help_colour: 509475
interface_help_colour_bright: 63b07a
hash_mismatch_panic: no

wallpaper: boot():/EFI/Omyvoid/omyvoid-boot.png
wallpaper_style: stretched
backdrop: 111c18
term_background: ff111c18
term_background_bright: 23372b
term_foreground: c1c497
term_foreground_bright: f7e8b2
term_palette: 090f0d;ff5345;549e6a;e5c736;509475;d2689c;2dd5b7;c1c497
term_palette_bright: 53685b;db9f9c;63b07a;e5c736;acd4cf;75bbb3;8cd3cb;f7e8b2
