timeout: 8
default_entry: 1
remember_last_entry: no
interface_branding: Omyvoid Bootloader
interface_branding_colour: 509475
interface_help_colour: 509475
interface_help_colour_bright: 63b07a
hash_mismatch_panic: no

wallpaper: boot():/boot/omyvoid-boot.png
wallpaper_style: stretched
backdrop: 111c18
term_background: ff111c18
term_background_bright: 23372b
term_foreground: c1c497
term_foreground_bright: f7e8b2
term_palette: 090f0d;ff5345;549e6a;e5c736;509475;d2689c;2dd5b7;c1c497
term_palette_bright: 53685b;db9f9c;63b07a;e5c736;acd4cf;75bbb3;8cd3cb;f7e8b2

/Start Omyvoid Live
protocol: linux
path: boot():/boot/vmlinuz
module_path: boot():/boot/initrd
cmdline: root=live:CDLABEL=OMYVOID_LIVE ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 rd.live.overlay.overlayfs=1 loglevel=3 gpt add_efi_memmap vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 live.autologin live.user=omyvoid live.shell=/bin/bash

/Start with safe graphics
protocol: linux
path: boot():/boot/vmlinuz
module_path: boot():/boot/initrd
cmdline: root=live:CDLABEL=OMYVOID_LIVE ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 rd.live.overlay.overlayfs=1 nomodeset module_blacklist=nouveau loglevel=4 gpt add_efi_memmap vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 live.autologin live.user=omyvoid live.shell=/bin/bash

/Open recovery
protocol: linux
path: boot():/boot/vmlinuz
module_path: boot():/boot/initrd
cmdline: root=live:CDLABEL=OMYVOID_LIVE ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 rd.live.overlay.overlayfs=1 loglevel=3 gpt add_efi_memmap vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 live.autologin live.user=omyvoid live.shell=/bin/bash omyvoid.autostart=recovery

/Start installer
protocol: linux
path: boot():/boot/vmlinuz
module_path: boot():/boot/initrd
cmdline: root=live:CDLABEL=OMYVOID_LIVE ro init=/sbin/init rd.luks=0 rd.md=0 rd.dm=0 rd.live.overlay.overlayfs=1 loglevel=3 gpt add_efi_memmap vconsole.unicode=1 vconsole.keymap=us locale.LANG=en_US.UTF-8 live.autologin live.user=omyvoid live.shell=/bin/bash omyvoid.autostart=installer
